app:
  env: "dev"

http:
  addr: ":8080"

databases:
  primary:
    driver: "postgres"
    dsn: "postgres://postgres:postgres@localhost:5432/orders?sslmode=disable"
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: "5m"
    conn_max_idle_time: "5m"
    log_level: "warn"
    slow_threshold: "200ms"
    skip_default_tx: false
    prepare_stmt: true