global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'observability-demo'
    static_configs:
      - targets: ['host.docker.internal:9090']
        labels:
          service: 'observability-demo'
